#=========================================================#
#                     Bot configuration                   #
#=========================================================#

BOT:
  NAME: "Djorr | Tickets"
  TOKEN: ""

#=========================================================#
#                   Tickets configuration                 #
#=========================================================#

TICKET:
  STAFF_ROLES:
    - "911961324253237318"
  TICKET_EMBED_CHANNEL: "999554565017960500"
  TICKET_LOG_CHANNEL: "999554575201751153"
  IMPORTANT_CATEGORIES:
    OPEN: "1005383475836239895"
    CLOSED: "1010683886629560431"
    OPEN_LATEN: "999554472516788276"
    ON_HOLD: "999554472516788276"

  CATEGORIES:
    MODERATION:
      CATEGORY_IDENTIFIER: "moderation"
      CATEGORY_ID: "1005383475836239895"
      CATEGORY_NAME: "Ontrechte ban/mute"
      TYPES:
        BAN:
          TICKET_IDENTIFIER: "moderation_ban"
          TICKET_PREFIX: "mb-"
          TICKET_DISPLAY_TOPIC: "Moderatie"
          TICKET_DISPLAY_NAME: "Ban"
          TICKET_TAG_ROLES:
            - "911961324253237318"
          TICKET_QUESTIONS:
            1:
              QUESTION: "Wat is je minecraft naam?"
              IS_YES_OR_NO_QUESTION: false
            2:
              QUESTION: "Wie heeft je verbannen?"
              IS_YES_OR_NO_QUESTION: false
        MUTE:
          TICKET_IDENTIFIER: "moderation_mute"
          TICKET_PREFIX: "mm-"
          TICKET_DISPLAY_TOPIC: "Moderatie"
          TICKET_DISPLAY_NAME: "Mute"
          TICKET_TAG_ROLES:
            - "911961324253237318"
          TICKET_QUESTIONS:
            1:
              QUESTION: "Wat is je minecraft naam?"
              IS_YES_OR_NO_QUESTION: false
            2:
              QUESTION: "Wie heeft je gemuted?"
              IS_YES_OR_NO_QUESTION: false
    MARKETING:
      CATEGORY_IDENTIFIER: "marketing"
      CATEGORY_ID: "1005383475836239895"
      CATEGORY_NAME: "Marketing (Partner/Media)"
      TYPES:
        MEDIA:
          TICKET_IDENTIFIER: "marketing_media"
          TICKET_PREFIX: "media-"
          TICKET_DISPLAY_TOPIC: "Marketing"
          TICKET_DISPLAY_NAME: "Media Aanvraag"
          TICKET_TAG_ROLES:
            - "911961324253237318"
          TICKET_QUESTIONS:
            1:
              QUESTION: "Wat voor platformen heb je?"
              IS_YES_OR_NO_QUESTION: false
            2:
              QUESTION: "Wat is de naam van je kanaal?"
              IS_YES_OR_NO_QUESTION: false
        PARTNER:
          TICKET_IDENTIFIER: "marketing_partner"
          TICKET_PREFIX: "partner-"
          TICKET_DISPLAY_TOPIC: "Marketing"
          TICKET_DISPLAY_NAME: "Partner Aanvraag"
          TICKET_TAG_ROLES:
            - "911961324253237318"
          TICKET_QUESTIONS:
            1:
              QUESTION: "Voor welke server wilt u adverteren?"
              IS_YES_OR_NO_QUESTION: false
            2:
              QUESTION: "Hoeveel leden verwacht u op onze te komen?"
              IS_YES_OR_NO_QUESTION: false
            3:
              QUESTION: "Stuur de discord link."
              IS_YES_OR_NO_QUESTION: false
    ISSUE:
      CATEGORY_IDENTIFIER: "issue"
      CATEGORY_ID: "1005383475836239895"
      CATEGORY_NAME: "Meldingen (Bugs/Reports)"
      TYPES:
        BUG:
          TICKET_IDENTIFIER: "issue_bug"
          TICKET_PREFIX: "ib-"
          TICKET_DISPLAY_TOPIC: "Meldingen"
          TICKET_DISPLAY_NAME: "Bug melden"
          TICKET_TAG_ROLES:
            - "911961324253237318"
          TICKET_QUESTIONS:
            1:
              QUESTION: "Wat is je minecraft naam?"
              IS_YES_OR_NO_QUESTION: false
            2:
              QUESTION: "Geef een duidelijke beschrijving van de bug."
              IS_YES_OR_NO_QUESTION: false
            3:
              QUESTION: "Op welke server vond deze bug plaats?"
              IS_YES_OR_NO_QUESTION: false
            4:
              QUESTION: "Hoeveel mensen hebben last van de bug? (Bv: Alleen jij)"
              IS_YES_OR_NO_QUESTION: false
        REPORT:
          TICKET_IDENTIFIER: "issue_report"
          TICKET_PREFIX: "ir-"
          TICKET_DISPLAY_TOPIC: "Meldingen"
          TICKET_DISPLAY_NAME: "Report melden"
          TICKET_TAG_ROLES:
            - "911961324253237318"
          TICKET_QUESTIONS:
            1:
              QUESTION: "Wat is je minecraft naam?"
              IS_YES_OR_NO_QUESTION: false
            2:
              QUESTION: "Wat is de naam van de speler die je wilt rapporteren?"
              IS_YES_OR_NO_QUESTION: false
            3:
              QUESTION: "Geef een duidelijke beschrijving van waarom je hem rapporteert. (Met bewijs!"
              IS_YES_OR_NO_QUESTION: false
    QUESTION:
      CATEGORY_IDENTIFIER: "question"
      CATEGORY_ID: "1005383475836239895"
      CATEGORY_NAME: "Vragen"
      TYPES:
        GENERAL_QUESTION:
          TICKET_IDENTIFIER: "question_vraag"
          TICKET_PREFIX: "qv-"
          TICKET_DISPLAY_TOPIC: "Questions"
          TICKET_DISPLAY_NAME: "Algemene Vraag"
          TICKET_TAG_ROLES:
            - "911961324253237318"
          TICKET_QUESTIONS:
            1:
              QUESTION: "Wat is je minecraft naam?"
              IS_YES_OR_NO_QUESTION: false
            2:
              QUESTION: "Heb je de #FAQ gelezen?"
              IS_YES_OR_NO_QUESTION: false
            3:
              QUESTION: "Stel je vraag."
              IS_YES_OR_NO_QUESTION: false
    APPLICATION:
      CATEGORY_IDENTIFIER: "application"
      CATEGORY_ID: "1005383475836239895"
      CATEGORY_NAME: "Sollicitaties"
      TYPES:
        DEVELOPER:
          TICKET_IDENTIFIER: "application_er"
          TICKET_PREFIX: "sd-"
          TICKET_DISPLAY_TOPIC: "Sollicitatie"
          TICKET_DISPLAY_NAME: "Developer"
          TICKET_TAG_ROLES:
            - "911961324253237318"
          TICKET_QUESTIONS:
            1:
              QUESTION: "Wat is uw naam in het echte leven?"
              IS_YES_OR_NO_QUESTION: false
            2:
              QUESTION: "Wat is uw naam in minecraft?"
              IS_YES_OR_NO_QUESTION: false
            3:
              QUESTION: "Wat is uw leeftijd?"
              IS_YES_OR_NO_QUESTION: false
            4:
              QUESTION: "Wat zijn uw ervaringen met developen?"
              IS_YES_OR_NO_QUESTION: false
            5:
              QUESTION: "In welke taal (talen) programmeert u?"
              IS_YES_OR_NO_QUESTION: false
            6:
              QUESTION: "Wat is uw motivatie om hier developer te worden?"
              IS_YES_OR_NO_QUESTION: false
            7:
              QUESTION: "Hoevaak bent u ongeveer online? En zijn er ook dagen wanneer u niet online bent?"
              IS_YES_OR_NO_QUESTION: false
            8:
              QUESTION: "Bent u op een andere server ook developer?"
              IS_YES_OR_NO_QUESTION: false
            9:
              QUESTION: "Accepteert u de staff-regels (https://neonmc.nl/staffrules) en heeft u nog wat extra's te zeggen?"
              IS_YES_OR_NO_QUESTION: false
        STAFF:
          TICKET_IDENTIFIER: "application_s"
          TICKET_PREFIX: "ss-"
          TICKET_DISPLAY_TOPIC: "Sollicitatie"
          TICKET_DISPLAY_NAME: "Staff"
          TICKET_TAG_ROLES:
            - "911961324253237318"
          TICKET_QUESTIONS:
            1:
              QUESTION: "Wat is uw naam in het echte leven?"
              IS_YES_OR_NO_QUESTION: false
            2:
              QUESTION: "Wat is uw naam in minecraft?"
              IS_YES_OR_NO_QUESTION: false
            3:
              QUESTION: "Wat is uw leeftijd?"
              IS_YES_OR_NO_QUESTION: false
            4:
              QUESTION: "Wat zijn uw ervaringen met staff zijn?"
              IS_YES_OR_NO_QUESTION: false
            5:
              QUESTION: "Waarom niet op een andere server?"
              IS_YES_OR_NO_QUESTION: false
            6:
              QUESTION: "Wat is uw motivatie om hier staff te worden?"
              IS_YES_OR_NO_QUESTION: false
            7:
              QUESTION: "Hoevaak bent u ongeveer online? En zijn er ook dagen wanneer u niet online bent?"
              IS_YES_OR_NO_QUESTION: false
            8:
              QUESTION: "Accepteert u de staff-regels (https://neonmc.nl/staffrules) en heeft u nog wat extra's te zeggen?"
              IS_YES_OR_NO_QUESTION: false
        EVENT:
          TICKET_IDENTIFIER: "application_e"
          TICKET_PREFIX: "se-"
          TICKET_DISPLAY_TOPIC: "Sollicitatie"
          TICKET_DISPLAY_NAME: "Event Team"
          TICKET_TAG_ROLES:
            - "911961324253237318"
          TICKET_QUESTIONS:
            1:
              QUESTION: "Wat is uw naam in het echte leven?"
              IS_YES_OR_NO_QUESTION: false
            2:
              QUESTION: "Wat is uw leeftijd?"
              IS_YES_OR_NO_QUESTION: false
            3:
              QUESTION: "Wat zijn uw ervaringen met event-staff zijn?"
              IS_YES_OR_NO_QUESTION: false
            4:
              QUESTION: "Waarom niet op een andere server?"
              IS_YES_OR_NO_QUESTION: false
            5:
              QUESTION: "Wat is uw motivatie om hier event-staff te worden?"
              IS_YES_OR_NO_QUESTION: false
            6:
              QUESTION: "Hoevaak bent u ongeveer online? En zijn er ook dagen wanneer u niet online bent?"
              IS_YES_OR_NO_QUESTION: false
            7:
              QUESTION: "Bent u op een andere server ook event-staff?"
              IS_YES_OR_NO_QUESTION: false
            8:
              QUESTION: "Accepteert u de staff-regels (https://neonmc.nl/staffrules) en heeft u nog wat extra's te zeggen?"
              IS_YES_OR_NO_QUESTION: false
        MARKETING:
          TICKET_IDENTIFIER: "application_m"
          TICKET_PREFIX: "sm-"
          TICKET_DISPLAY_TOPIC: "Sollicitatie"
          TICKET_DISPLAY_NAME: "Marketing"
          TICKET_TAG_ROLES:
            - "911961324253237318"
          TICKET_QUESTIONS:
            1:
              QUESTION: "Wat is uw naam in het echte leven?"
              IS_YES_OR_NO_QUESTION: false
            2:
              QUESTION: "Wat is uw naam in minecraft?"
              IS_YES_OR_NO_QUESTION: false
            3:
              QUESTION: "Wat is uw leeftijd?"
              IS_YES_OR_NO_QUESTION: false
            4:
              QUESTION: "Wat zijn uw ervaringen met marketing-staff zijn?"
              IS_YES_OR_NO_QUESTION: false
            5:
              QUESTION: "Wat is uw motivatie om hier marketing-staff te worden?"
              IS_YES_OR_NO_QUESTION: false
            6:
              QUESTION: "Hoevaak bent u ongeveer online? En zijn er ook dagen wanneer u niet online bent?"
              IS_YES_OR_NO_QUESTION: false
            7:
              QUESTION: "Bent u op een andere server ook marketing-staff?"
              IS_YES_OR_NO_QUESTION: false
            8:
              QUESTION: "Accepteert u de staff-regels (https://neonmc.nl/staffrules) en heeft u nog wat extra's te zeggen?"
              IS_YES_OR_NO_QUESTION: false
